service: rs-ec-2021-loadtest
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ${env:AWS_REGION, us-east-1}
  stage: dev
  httpApi:
    metrics: true

package:
  excludeDevDependencies: true
  exclude:
    - node_modules
    - README.md
    - .gitignore
    - .git
    - .nvmrc
    - .editorconfig
    - .eslintrc
    - .env
    - docker
    - Makefile
    - .github
    - tests

functions:
  api:
    memorySize: 128
    reservedConcurrency: 10
    timeout: 29
    handler: api/handler.handler
    events:
      - httpApi:
          path: /hello
          method: GET
      - httpApi:
          path: /hello/{name}
          method: GET
